# install-services.yml
---
  - hosts: all
    become: true
    tasks:
      - name: Installing services
        yum:
          name:
            - httpd
            - php
          state: present
      - name: Ensure apache starts
        service: name=httpd state=started enabled=yes